site_name: Carbon for Lua
theme: readthedocs
repo_url: https://github.com/lua-carbon/carbon
pages:
- [index.md, Index]
- [Getting Started.md, Tutorials, Getting Started]
- [Types.md, Tutorials, Carbon Types]
- [Classes/Carbide.md, Classes, Carbide]
- [Classes/Collections.Dictionary.md, Classes, Collections.Dictionary]
- [Classes/Collections.List.md, Classes, Collections.List]
- [Classes/Collections.Set.md, Classes, Collections.Set]
- [Classes/Collections.Tuple.md, Classes, Collections.Tuple]
- [Classes/Configuration.md, Classes, Configuration]
- [Classes/CopyBarrier.md, Classes, CopyBarrier]
- [Classes/Exception.md, Classes, Exception]
- [Classes/Exceptions.CodeGenerationException.md, Classes, Exceptions.CodeGenerationException]
- [Classes/Exceptions.NotImplementedException.md, Classes, Exceptions.NotImplementedException]
- [Classes/IO.md, Classes, IO]
- [Classes/IO.File.md, Classes, IO.File]
- [Classes/Math.Color.md, Classes, Math.Color]
- [Classes/Math.ColorRGB.md, Classes, Math.ColorRGB]
- [Classes/Math.ColorRGBA.md, Classes, Math.ColorRGBA]
- [Classes/Math.FastMatrix.md, Classes, Math.FastMatrix]
- [Classes/Math.Matrix2x2.md, Classes, Math.Matrix2x2]
- [Classes/Math.Matrix4x4.md, Classes, Math.Matrix4x4]
- [Classes/Math.Quaternion.md, Classes, Math.Quaternion]
- [Classes/Math.Vector.md, Classes, Math.Vector]
- [Classes/Math.Vector2.md, Classes, Math.Vector2]
- [Classes/Math.Vector3.md, Classes, Math.Vector3]
- [Classes/Math.Vector4.md, Classes, Math.Vector4]
- [Classes/Matrix3x3.md, Classes, Matrix3x3]
- [Classes/Metadata.md, Classes, Metadata]
- [Classes/Nanotube.md, Classes, Nanotube]
- [Classes/OOP.md, Classes, OOP]
- [Classes/OOP.BaseClass.md, Classes, OOP.BaseClass]
- [Classes/OOP.Object.md, Classes, OOP.Object]
- [Classes/OOP.StaticObject.md, Classes, OOP.StaticObject]
- [Classes/Operators.md, Classes, Operators]
- [Classes/Pointers.BasicPointer.md, Classes, Pointers.BasicPointer]
- [Classes/Pointers.ForwardPointer.md, Classes, Pointers.ForwardPointer]
- [Classes/Pointers.LookupPointer.md, Classes, Pointers.LookupPointer]
- [Classes/Pointers.WeakPointer.md, Classes, Pointers.WeakPointer]
- [Classes/Promise.md, Classes, Promise]
- [Classes/Serializable.md, Classes, Serializable]
- [Classes/TemplateEngine.md, Classes, TemplateEngine]
- [Classes/Testing.md, Classes, Testing]
- [Classes/Testing.TestResult.md, Classes, Testing.TestResult]
- [Classes/Time.md, Classes, Time]
- [style.css]