site_name: Carbon for Lua
theme: readthedocs
repo_url: https://github.com/lua-carbon/carbon
extra_css:
- style.css
pages:
- Index: index.md
- Tutorials:
  - Getting Started: Getting_Started.md
  - Using Carbide: Using_Carbide.md
  - Carbon Types: Types.md
- Classes:
  - Bench: Classes/Bench.md
  - Callisto: Classes/Callisto.md
  - Callisto.Compiler: Classes/Callisto.Compiler.md
  - Carbide: Classes/Carbide.md
  - Carbon: Classes/Carbon.md
  - Collections.Dictionary: Classes/Collections.Dictionary.md
  - Collections.List: Classes/Collections.List.md
  - Collections.Set: Classes/Collections.Set.md
  - Collections.Tuple: Classes/Collections.Tuple.md
  - CopyBarrier: Classes/CopyBarrier.md
  - Exception: Classes/Exception.md
  - Exceptions.CodeGenerationException: Classes/Exceptions.CodeGenerationException.md
  - Exceptions.NotImplementedException: Classes/Exceptions.NotImplementedException.md
  - Exceptions.SyntaxErrorException: Classes/Exceptions.SyntaxErrorException.md
  - Functional: Classes/Functional.md
  - IO: Classes/IO.md
  - IO.File: Classes/IO.File.md
  - Logging: Classes/Logging.md
  - Math.CMatrix4x4: Classes/Math.CMatrix4x4.md
  - Math.Color: Classes/Math.Color.md
  - Math.ColorRGB: Classes/Math.ColorRGB.md
  - Math.ColorRGBA: Classes/Math.ColorRGBA.md
  - Math.Matrix: Classes/Math.Matrix.md
  - Math.Matrix2x2: Classes/Math.Matrix2x2.md
  - Math.Matrix3x3: Classes/Math.Matrix3x3.md
  - Math.Matrix4x4: Classes/Math.Matrix4x4.md
  - Math.Quaternion: Classes/Math.Quaternion.md
  - Math.Vector: Classes/Math.Vector.md
  - Math.Vector2: Classes/Math.Vector2.md
  - Math.Vector3: Classes/Math.Vector3.md
  - Math.Vector4: Classes/Math.Vector4.md
  - Metadata: Classes/Metadata.md
  - Nanotube: Classes/Nanotube.md
  - OOP: Classes/OOP.md
  - OOP.BaseClass: Classes/OOP.BaseClass.md
  - OOP.Object: Classes/OOP.Object.md
  - OOP.StaticObject: Classes/OOP.StaticObject.md
  - Operators: Classes/Operators.md
  - Pointers.BasicPointer: Classes/Pointers.BasicPointer.md
  - Pointers.ForwardPointer: Classes/Pointers.ForwardPointer.md
  - Pointers.LookupPointer: Classes/Pointers.LookupPointer.md
  - Pointers.WeakPointer: Classes/Pointers.WeakPointer.md
  - Promise: Classes/Promise.md
  - Serializable: Classes/Serializable.md
  - Serialization: Classes/Serialization.md
  - Serialization.Format: Classes/Serialization.Format.md
  - Serialization.Formats.SimpleJSON: Classes/Serialization.Formats.SimpleJSON.md
  - TemplateEngine: Classes/TemplateEngine.md
  - Testing: Classes/Testing.md
  - Testing.TestResult: Classes/Testing.TestResult.md
  - Time: Classes/Time.md
