site_name: Carbon for Lua
theme: readthedocs
repo_url: https://github.com/lua-carbon/carbon
pages:
- [index.md, Index]
- [Getting Started.md, Tutorials, Getting Started]
- [Classes/Collections.Dictionary.md, Classes, Collections.Dictionary]
- [Classes/Collections.List.md, Classes, Collections.List]
- [Classes/Collections.Set.md, Classes, Collections.Set]
- [Classes/Collections.Tuple.md, Classes, Collections.Tuple]
- [Classes/Configuration.md, Classes, Configuration]
- [Classes/Exception.md, Classes, Exception]
- [Classes/OOP.Object.md, Classes, OOP.Object]
- [Classes/OOP.StaticObject.md, Classes, OOP.StaticObject]